### ISSUE TITLE
Doensn't install for version 12.13.1 of node.js

### ISSUE THREAD

**Issue by alxolr** [dumbmatter/sas7bdat-js#3]
It seems the package fs-ext it's not building for version 12.x for current version

../fs-ext.cc: In function ‘Nan::NAN_METHOD_RETURN_TYPE Fcntl(Nan::NAN_METHOD_ARGS_TYPE)’:
../fs-ext.cc:369:32: error: no matching function for call to ‘v8::Value::Int32Value()’
   int fd = info[0]->Int32Value();
                                ^
In file included from /home/alxolr/.cache/node-gyp/12.13.1/include/node/node.h:63:0,
                 from ../fs-ext.cc:20:
/home/alxolr/.cache/node-gyp/12.13.1/include/node/v8.h:2613:40: note: candidate: v8::Maybe<int> v8::Value::Int32Value(v8::Local<v8::Context>) const
   V8_WARN_UNUSED_RESULT Maybe<int32_t> Int32Value(Local<Context> context) const;
                                        ^~~~~~~~~~
/home/alxolr/.cache/node-gyp/12.13.1/include/node/v8.h:2613:40: note:   candidate expects 1 argument, 0 provided
../fs-ext.cc:370:33: error: no matching function for call to ‘v8::Value::Int32Value()’
   int cmd = info[1]->Int32Value();

> It seems it fails for fs-ext module, ideea to upgrade the fs-ext module version.

**Comment by dumbmatter** [comment]
Thanks! You are right, upgrading fs-ext fixed it. I just released v0.1.6 with this fix.
